package com.aichat.app.ui.theme

import androidx.compose.ui.graphics.Color

// 月下主题 - 深蓝夜空 + 银白月光
val md_theme_light_primary = Color(0xFF4A6FA5)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD4E4F7)
val md_theme_light_onPrimaryContainer = Color(0xFF1A2332)
val md_theme_light_secondary = Color(0xFF7B8FA8)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8EDF3)
val md_theme_light_onSecondaryContainer = Color(0xFF1E2A3A)
val md_theme_light_tertiary = Color(0xFFB8C5D6)
val md_theme_light_onTertiary = Color(0xFF1A2332)
val md_theme_light_tertiaryContainer = Color(0xFFF0F4F8)
val md_theme_light_onTertiaryContainer = Color(0xFF2C3E50)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF5F7FA)
val md_theme_light_onBackground = Color(0xFF1A2332)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1A2332)
val md_theme_light_surfaceVariant = Color(0xFFE8EDF3)
val md_theme_light_onSurfaceVariant = Color(0xFF4A5568)
val md_theme_light_outline = Color(0xFF8A9AAF)
val md_theme_light_inverseOnSurface = Color(0xFFF0F4F8)
val md_theme_light_inverseSurface = Color(0xFF2C3E50)
val md_theme_light_inversePrimary = Color(0xFF8FB8E8)
val md_theme_light_surfaceTint = Color(0xFF4A6FA5)

val md_theme_dark_primary = Color(0xFF8FB8E8)
val md_theme_dark_onPrimary = Color(0xFF1A2332)
val md_theme_dark_primaryContainer = Color(0xFF2C4A6E)
val md_theme_dark_onPrimaryContainer = Color(0xFFD4E4F7)
val md_theme_dark_secondary = Color(0xFF9FB4CC)
val md_theme_dark_onSecondary = Color(0xFF1E2A3A)
val md_theme_dark_secondaryContainer = Color(0xFF3A4F6A)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8EDF3)
val md_theme_dark_tertiary = Color(0xFFC5D4E8)
val md_theme_dark_onTertiary = Color(0xFF1A2332)
val md_theme_dark_tertiaryContainer = Color(0xFF4A5F7A)
val md_theme_dark_onTertiaryContainer = Color(0xFFF0F4F8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0F1729)
val md_theme_dark_onBackground = Color(0xFFE0E6F0)
val md_theme_dark_surface = Color(0xFF1A2332)
val md_theme_dark_onSurface = Color(0xFFE0E6F0)
val md_theme_dark_surfaceVariant = Color(0xFF2C3E50)
val md_theme_dark_onSurfaceVariant = Color(0xFFB0C0D4)
val md_theme_dark_outline = Color(0xFF5A6F8A)
val md_theme_dark_inverseOnSurface = Color(0xFF0F1729)
val md_theme_dark_inverseSurface = Color(0xFFE0E6F0)
val md_theme_dark_inversePrimary = Color(0xFF4A6FA5)
val md_theme_dark_surfaceTint = Color(0xFF8FB8E8)
